import type { CSSProperties } from 'react';

export const styles = {
  page: {
    background:
      'radial-gradient(circle at 18% 10%, rgba(218, 165, 32, 0.16), transparent 28%), linear-gradient(135deg, var(--page-bg), var(--page-bg))',
    color: 'var(--text)',
    display: 'flex',
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    minHeight: '100vh',
    minWidth: 0,
    width: '100%',
  },
  pageCompact: {
    display: 'block',
  },
  sidebar: {
    background: 'var(--panel-bg)',
    borderRight: '1px solid var(--border)',
    boxSizing: 'border-box',
    flex: '0 0 248px',
    overflow: 'hidden',
    padding: '24px',
    transition: 'flex-basis 220ms ease, width 220ms ease, padding 220ms ease, border-color 220ms ease',
    width: '248px',
  },
  sidebarCollapsed: {
    flex: '0 0 92px',
    padding: '20px 14px',
    width: '92px',
  },
  mobileHeader: {
    alignItems: 'center',
    background: 'var(--panel-bg)',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    justifyContent: 'space-between',
    padding: '10px 14px',
    position: 'sticky',
    top: 0,
    zIndex: 20,
  },
  mobileBrand: {
    alignItems: 'center',
    display: 'flex',
    gap: '10px',
    minWidth: 0,
  },
  mobileBrandText: {
    display: 'grid',
    gap: '2px',
    minWidth: 0,
  },
  mobileHeaderActions: {
    alignItems: 'center',
    display: 'flex',
    gap: '8px',
  },
  mobileCurrentView: {
    color: 'var(--muted)',
    display: 'block',
    fontSize: '12px',
    fontWeight: 700,
    lineHeight: 1.1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  mobileLogo: {
    borderRadius: '6px',
    display: 'block',
    height: '44px',
    objectFit: 'contain',
    width: '44px',
  },
  hamburgerButton: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--text)',
    cursor: 'pointer',
    display: 'grid',
    gap: '4px',
    height: '42px',
    justifyContent: 'center',
    padding: '0 10px',
    width: '46px',
  },
  hamburgerGlyph: {
    fontSize: '12px',
    fontWeight: 800,
    letterSpacing: 0,
    lineHeight: 1,
  },
  mobileDrawerOverlay: {
    alignItems: 'flex-start',
    background: 'rgba(0, 0, 0, 0.48)',
    bottom: 0,
    display: 'flex',
    left: 0,
    padding: '12px',
    position: 'fixed',
    right: 0,
    top: 0,
    zIndex: 40,
  },
  mobileDrawer: {
    background: 'var(--panel-bg)',
    borderRight: '1px solid var(--border)',
    borderRadius: '10px',
    boxShadow: '18px 0 44px rgba(0, 0, 0, 0.35)',
    display: 'grid',
    gap: '12px',
    gridTemplateRows: 'auto auto auto',
    maxHeight: 'calc(100dvh - 24px)',
    maxWidth: '300px',
    overflowY: 'auto',
    padding: '18px',
    width: 'min(82vw, 300px)',
  },
  mobileDrawerHeader: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  mobileDrawerNav: {
    display: 'grid',
    gap: '8px',
  },
  mobileDrawerNavButton: {
    minHeight: '44px',
    width: '100%',
  },
  mobileDrawerActions: {
    display: 'grid',
    gap: '10px',
    marginTop: '8px',
  },
  logoRow: {
    alignItems: 'center',
    display: 'flex',
    gap: '10px',
    marginBottom: '32px',
    minHeight: '64px',
    transition: 'gap 220ms ease, margin 220ms ease, min-height 220ms ease',
  },
  logoRowCollapsed: {
    display: 'grid',
    gap: '12px',
    justifyItems: 'center',
    marginBottom: '24px',
    minHeight: '112px',
  },
  logoText: {
    fontSize: '15px',
    lineHeight: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
  },
  sidebarToggle: {
    backgroundColor: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    color: 'var(--text)',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 800,
    marginLeft: 'auto',
    minHeight: '32px',
    minWidth: '32px',
    transition: 'background 180ms ease, border-color 180ms ease, color 180ms ease, transform 220ms ease',
  },
  sidebarToggleCollapsed: {
    marginLeft: 0,
  },
  logoMark: {
    borderRadius: '6px',
    display: 'block',
    flex: '0 0 64px',
    height: '64px',
    objectFit: 'contain',
    transition: 'height 220ms ease, width 220ms ease, flex-basis 220ms ease, transform 220ms ease',
    width: '64px',
  },
  logoMarkCollapsed: {
    flexBasis: '56px',
    height: '56px',
    width: '56px',
  },
  nav: {
    display: 'grid',
    gap: '6px',
  },
  navCompact: {
    display: 'flex',
    gap: '8px',
    overflowX: 'auto',
    paddingBottom: '2px',
  },
  navItem: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    border: 0,
    borderRadius: '6px',
    color: 'var(--muted)',
    cursor: 'pointer',
    display: 'flex',
    fontSize: '14px',
    gap: '10px',
    minHeight: '42px',
    padding: '10px 12px',
    textAlign: 'left',
    transition:
      'background 180ms ease, color 180ms ease, padding 220ms ease, min-height 220ms ease, border-color 180ms ease',
    whiteSpace: 'nowrap',
  },
  navActive: {
    alignItems: 'center',
    backgroundColor: 'var(--accent-soft)',
    border: 0,
    borderRadius: '6px',
    color: 'var(--accent)',
    cursor: 'pointer',
    display: 'flex',
    fontSize: '14px',
    gap: '10px',
    fontWeight: 700,
    minHeight: '42px',
    padding: '10px 12px',
    textAlign: 'left',
    transition:
      'background 180ms ease, color 180ms ease, padding 220ms ease, min-height 220ms ease, border-color 180ms ease',
    whiteSpace: 'nowrap',
  },
  navItemCollapsed: {
    justifyContent: 'center',
    minHeight: '50px',
    padding: '8px 6px',
    textAlign: 'center',
  },
  navMonogram: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--muted)',
    display: 'inline-grid',
    flex: '0 0 28px',
    fontSize: '11px',
    fontWeight: 900,
    height: '28px',
    justifyContent: 'center',
    letterSpacing: 0,
    lineHeight: 1,
    transition:
      'background 180ms ease, border-color 180ms ease, color 180ms ease, height 220ms ease, width 220ms ease, flex-basis 220ms ease',
    width: '28px',
  },
  navMonogramActive: {
    background: 'var(--accent)',
    border: '1px solid var(--accent)',
    color: '#111827',
  },
  navMonogramCollapsed: {
    flexBasis: '42px',
    fontSize: '13px',
    height: '42px',
    width: '42px',
  },
  navLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  content: {
    flex: 1,
    minWidth: 0,
    padding: 'clamp(20px, 3vw, 32px)',
    transition: 'padding 220ms ease',
  },
  contentCompact: {
    overflowX: 'hidden',
    padding: '14px 14px 108px',
  },
  topbarMobileHidden: {
    display: 'none',
  },
  topbar: {
    alignItems: 'center',
    display: 'flex',
    gap: '16px',
    justifyContent: 'space-between',
    marginBottom: '24px',
    flexWrap: 'wrap',
    width: '100%',
  },
  topbarIntro: {
    flex: '1 1 320px',
    minWidth: 0,
  },
  topbarActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    justifyContent: 'flex-end',
    marginLeft: 'auto',
  },
  bootLoaderPage: {
    alignItems: 'center',
    display: 'grid',
    minHeight: '100vh',
    padding: '24px',
    placeItems: 'center',
    width: '100%',
  },
  bootLoaderCard: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '16px',
    boxShadow: '0 24px 60px rgba(0, 0, 0, 0.28)',
    display: 'grid',
    gap: '18px',
    justifyItems: 'center',
    maxWidth: '420px',
    padding: '28px 24px',
    textAlign: 'center',
    width: 'min(100%, 420px)',
  },
  bootLoaderLogoFrame: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '18px',
    display: 'flex',
    height: '96px',
    justifyContent: 'center',
    padding: '12px',
    width: '96px',
  },
  bootLoaderLogo: {
    display: 'block',
    height: '72px',
    objectFit: 'contain',
    width: '72px',
  },
  bootLoaderTitle: {
    fontSize: '24px',
    lineHeight: 1.15,
    margin: 0,
  },
  bootLoaderSubtitle: {
    color: 'var(--muted)',
    fontSize: '14px',
    margin: 0,
  },
  bootLoaderProgressTrack: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    height: '12px',
    overflow: 'hidden',
    width: '100%',
  },
  bootLoaderProgressFill: {
    background: 'linear-gradient(90deg, #d4a017, #f5c84c)',
    borderRadius: '999px',
    height: '100%',
    transition: 'width 180ms ease',
  },
  bootLoaderProgressText: {
    color: 'var(--muted)',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: 0,
  },
  notificationButton: {
    alignItems: 'center',
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    color: 'var(--text)',
    cursor: 'pointer',
    display: 'inline-flex',
    gap: '8px',
    minHeight: '40px',
    padding: '8px 12px',
    position: 'relative',
  },
  notificationGlyph: {
    fontSize: '12px',
    fontWeight: 800,
    lineHeight: 1,
  },
  notificationBadge: {
    alignItems: 'center',
    background: 'var(--accent)',
    borderRadius: '999px',
    color: 'var(--accent-contrast)',
    display: 'inline-flex',
    fontSize: '12px',
    fontWeight: 800,
    justifyContent: 'center',
    minWidth: '22px',
    padding: '2px 6px',
  },
  notificationPanel: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '10px',
    display: 'grid',
    gap: '14px',
    marginBottom: '18px',
    padding: '16px',
  },
  notificationSection: {
    display: 'grid',
    gap: '10px',
  },
  notificationItem: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '6px',
    padding: '12px',
  },
  platformWorkspace: {
    display: 'grid',
    gap: '18px',
  },
  platformWorkspaceHeader: {
    alignItems: 'flex-start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '14px',
    justifyContent: 'space-between',
  },
  platformSectionNav: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
  },
  platformSectionButton: {
    backgroundColor: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    color: 'var(--muted)',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 700,
    minHeight: '38px',
    padding: '8px 14px',
  },
  platformSectionButtonActive: {
    backgroundColor: 'var(--accent-soft)',
    border: '1px solid var(--accent)',
    borderRadius: '999px',
    color: 'var(--accent)',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 800,
    minHeight: '38px',
    padding: '8px 14px',
  },
  platformSelectField: {
    display: 'grid',
    gap: '6px',
    minWidth: '220px',
  },
  labelCaption: {
    color: 'var(--muted)',
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  select: {
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--text)',
    font: 'inherit',
    minHeight: '42px',
    padding: '10px 11px',
  },
  platformImmediateList: {
    display: 'grid',
    gap: '16px',
  },
  platformImmediatePanel: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '10px',
    padding: '16px',
  },
  platformImmediateTitle: {
    fontSize: '18px',
    margin: 0,
  },
  platformImmediateItem: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--text)',
    cursor: 'pointer',
    display: 'grid',
    gap: '4px',
    padding: '12px',
    textAlign: 'left',
  },
  platformFilterBar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '14px',
  },
  platformFilterStack: {
    display: 'grid',
    gap: '4px',
  },
  platformFilterButton: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    color: 'var(--muted)',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 700,
    minHeight: '36px',
    padding: '6px 12px',
  },
  platformFilterButtonActive: {
    background: 'var(--accent-soft)',
    border: '1px solid var(--accent)',
    borderRadius: '999px',
    color: 'var(--accent)',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 800,
    minHeight: '36px',
    padding: '6px 12px',
  },
  platformMembershipCard: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '14px',
    padding: '16px',
  },
  platformMembershipHeader: {
    alignItems: 'start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    justifyContent: 'space-between',
  },
  platformMembershipFacts: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginTop: '6px',
  },
  platformMembershipPaymentPanel: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '12px',
    padding: '12px',
  },
  platformMembershipActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
  },
  platformMembershipMeta: {
    color: 'var(--muted)',
    fontSize: '12px',
    fontWeight: 600,
  },
  platformSignupCard: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '12px',
    padding: '14px',
  },
  platformFiscalCard: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '12px',
    padding: '14px',
  },
  platformSignupFacts: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginTop: '6px',
  },
  platformSignupActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
  },
  buttonWithIcon: {
    alignItems: 'center',
    display: 'inline-flex',
    gap: '8px',
  },
  title: {
    fontSize: '28px',
    lineHeight: 1.15,
    margin: 0,
  },
  subtitle: {
    color: 'var(--muted)',
    fontSize: '15px',
    margin: '8px 0 0',
  },
  bottomTabBar: {
    background: 'var(--panel-bg)',
    borderTop: '1px solid var(--border)',
    bottom: 0,
    display: 'grid',
    gap: '4px',
    gridTemplateColumns: 'repeat(4, 1fr)',
    left: 0,
    padding: '8px 8px 10px',
    position: 'fixed',
    right: 0,
    zIndex: 30,
  },
  bottomTab: {
    alignItems: 'center',
    background: 'transparent',
    border: 0,
    borderRadius: '8px',
    color: 'var(--muted)',
    cursor: 'pointer',
    display: 'grid',
    fontSize: '11px',
    fontWeight: 700,
    gap: '3px',
    justifyItems: 'center',
    minHeight: '48px',
  },
  bottomTabActive: {
    alignItems: 'center',
    background: 'var(--accent-soft)',
    border: 0,
    borderRadius: '8px',
    color: 'var(--accent)',
    cursor: 'pointer',
    display: 'grid',
    fontSize: '11px',
    fontWeight: 800,
    gap: '3px',
    justifyItems: 'center',
    minHeight: '48px',
  },
  errorBanner: {
    background: 'var(--danger-bg)',
    border: '1px solid var(--danger)',
    borderRadius: '8px',
    color: 'var(--danger)',
    margin: '0 0 20px',
    padding: '12px 14px',
  },
  secondaryButton: {
    backgroundColor: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    color: 'var(--text)',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 700,
    padding: '10px 14px',
  },
  secondaryButtonActive: {
    backgroundColor: 'var(--accent-soft)',
    border: '1px solid var(--accent)',
    borderRadius: '6px',
    color: 'var(--text)',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 700,
    padding: '10px 14px',
  },
  primaryButton: {
    backgroundColor: 'var(--accent)',
    border: 0,
    borderRadius: '6px',
    color: 'var(--accent-contrast)',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 700,
    padding: '10px 14px',
  },
  metrics: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 170px), 1fr))',
    marginBottom: '24px',
  },
  metricCard: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    minWidth: 0,
    overflow: 'hidden',
    padding: 'clamp(14px, 3vw, 20px)',
  },
  metricLabel: {
    color: 'var(--muted)',
    fontSize: '13px',
    fontWeight: 700,
    margin: 0,
    textTransform: 'uppercase',
  },
  metricValue: {
    display: 'block',
    fontSize: 'clamp(22px, 6vw, 30px)',
    lineHeight: 1.1,
    marginTop: '10px',
    overflowWrap: 'anywhere',
  },
  gridTwo: {
    display: 'grid',
    gap: '20px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 360px), 1fr))',
    marginBottom: '20px',
  },
  workspaceGrid: {
    display: 'grid',
    gap: '20px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 420px), 1fr))',
  },
  profileGrid: {
    display: 'grid',
    gap: '20px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 420px), 1fr))',
  },
  companyWorkspace: {
    display: 'grid',
    gap: '18px',
  },
  companyWorkspaceHeader: {
    alignItems: 'flex-start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '14px',
    justifyContent: 'space-between',
  },
  formGridTwo: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
  },
  presetGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  formPanel: {
    alignSelf: 'start',
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '14px',
    padding: '20px',
  },
  companyLogoCard: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'minmax(96px, 128px) minmax(0, 1fr)',
    padding: '16px',
  },
  companyLogoPreviewFrame: {
    alignItems: 'center',
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '10px',
    display: 'flex',
    height: '120px',
    justifyContent: 'center',
    overflow: 'hidden',
    padding: '10px',
    width: '120px',
  },
  companyLogoPreviewImage: {
    display: 'block',
    height: '100%',
    objectFit: 'contain',
    width: '100%',
  },
  companyLogoInfo: {
    display: 'grid',
    gap: '8px',
  },
  tablePanel: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    minWidth: 0,
    overflowX: 'auto',
  },
  panelHeader: {
    alignItems: 'center',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    justifyContent: 'space-between',
    padding: '18px 20px',
  },
  panelHeaderCompact: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
  },
  smartHeader: {
    alignItems: 'center',
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    justifyContent: 'space-between',
    marginBottom: '16px',
    padding: '18px 20px',
  },
  panelTitle: {
    fontSize: '18px',
    margin: 0,
  },
  table: {
    borderCollapse: 'collapse',
    minWidth: '680px',
    width: '100%',
  },
  th: {
    color: 'var(--muted)',
    fontSize: '12px',
    padding: '12px 20px',
    textAlign: 'left',
    textTransform: 'uppercase',
  },
  thRight: {
    color: 'var(--muted)',
    fontSize: '12px',
    padding: '12px 20px',
    textAlign: 'right',
    textTransform: 'uppercase',
  },
  td: {
    borderTop: '1px solid var(--border)',
    fontSize: '14px',
    padding: '14px 20px',
    verticalAlign: 'top',
  },
  tdRight: {
    borderTop: '1px solid var(--border)',
    fontSize: '14px',
    fontWeight: 700,
    padding: '14px 20px',
    textAlign: 'right',
    verticalAlign: 'top',
  },
  mobileDataList: {
    display: 'grid',
    gap: '10px',
    padding: '12px',
  },
  mobileDataCard: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '8px',
    minWidth: 0,
    padding: '12px',
  },
  mobileDataRow: {
    alignItems: 'start',
    borderTop: '1px solid var(--border)',
    display: 'grid',
    gap: '8px',
    gridTemplateColumns: 'minmax(84px, 0.8fr) minmax(0, 1.2fr)',
    overflowWrap: 'anywhere',
    paddingTop: '8px',
  },
  label: {
    color: 'var(--text)',
    display: 'grid',
    fontSize: '14px',
    fontWeight: 600,
    gap: '7px',
  },
  input: {
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    color: 'var(--text)',
    font: 'inherit',
    padding: '10px 11px',
  },
  textarea: {
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    color: 'var(--text)',
    font: 'inherit',
    padding: '10px 11px',
    resize: 'vertical',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginTop: '4px',
  },
  linkButton: {
    background: 'transparent',
    border: 0,
    color: 'var(--accent)',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 700,
    marginRight: '10px',
    padding: 0,
  },
  whatsAppButton: {
    background: 'rgba(37, 211, 102, 0.14)',
    border: '1px solid rgba(37, 211, 102, 0.5)',
    borderRadius: '999px',
    color: '#25d366',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 800,
    padding: '6px 10px',
  },
  whatsAppIconButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(37, 211, 102, 0.14)',
    border: '1px solid rgba(37, 211, 102, 0.42)',
    borderRadius: '8px',
    color: '#25d366',
    cursor: 'pointer',
    display: 'inline-flex',
    height: '36px',
    justifyContent: 'center',
    width: '36px',
  },
  dangerButton: {
    background: 'transparent',
    border: 0,
    color: 'var(--danger)',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 700,
    padding: 0,
  },
  iconActionButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--accent)',
    cursor: 'pointer',
    display: 'inline-flex',
    height: '34px',
    justifyContent: 'center',
    width: '34px',
  },
  iconDangerButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    border: '1px solid rgba(239, 68, 68, 0.5)',
    borderRadius: '8px',
    color: 'var(--danger)',
    cursor: 'pointer',
    display: 'inline-flex',
    height: '34px',
    justifyContent: 'center',
    width: '34px',
  },
  dangerOutlineButton: {
    background: 'transparent',
    border: '1px solid var(--danger)',
    borderRadius: '6px',
    color: 'var(--danger)',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 700,
    padding: '10px 14px',
  },
  emptyState: {
    color: 'var(--muted)',
    margin: 0,
    padding: '24px 20px',
  },
  clientList: {
    display: 'grid',
    gap: '8px',
    padding: '12px',
  },
  clientRow: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '14px',
    gridTemplateColumns: 'minmax(140px, 1fr) minmax(180px, 1.1fr) minmax(110px, auto) auto',
    padding: '14px 16px',
  },
  clientRowCompact: {
    alignItems: 'stretch',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: '12px',
  },
  clientRowButton: {
    alignItems: 'center',
    background: 'transparent',
    border: 0,
    color: 'var(--text)',
    cursor: 'pointer',
    display: 'grid',
    gap: '14px',
    gridTemplateColumns: 'minmax(140px, 1fr) minmax(180px, 1.1fr) minmax(110px, auto)',
    minWidth: 0,
    padding: 0,
    textAlign: 'left',
  },
  clientRowButtonCompact: {
    alignItems: 'start',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: '10px',
  },
  clientIdentity: {
    display: 'grid',
    gap: '4px',
    minWidth: 0,
  },
  clientContact: {
    display: 'grid',
    gap: '4px',
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  clientContactLine: {
    alignItems: 'center',
    display: 'flex',
    gap: '8px',
    minWidth: 0,
  },
  clientContactLineMuted: {
    alignItems: 'center',
    color: 'var(--muted)',
    display: 'flex',
    fontSize: '13px',
    gap: '8px',
    minWidth: 0,
  },
  clientContactValue: {
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  clientMetaStack: {
    alignItems: 'start',
    display: 'grid',
    gap: '6px',
    justifyItems: 'start',
    minWidth: 0,
  },
  clientMetaPill: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    color: 'var(--text)',
    display: 'inline-flex',
    fontSize: '12px',
    fontWeight: 700,
    lineHeight: 1,
    padding: '6px 10px',
    whiteSpace: 'nowrap',
  },
  clientActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    justifyContent: 'flex-end',
  },
  clientActionsCompact: {
    justifyContent: 'flex-start',
  },
  clientRecordShell: {
    display: 'grid',
    gap: '16px',
    padding: '16px 20px 20px',
  },
  clientOverviewBar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
  },
  compactEmpty: {
    color: 'var(--muted)',
    fontSize: '14px',
    margin: 0,
  },
  categoryGrid: {
    display: 'grid',
    gap: '12px',
    padding: '20px',
  },
  categoryRow: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'flex',
    gap: '10px',
    justifyContent: 'space-between',
    padding: '13px 15px',
  },
  panelSubtitle: {
    color: 'var(--muted)',
    fontSize: '13px',
    margin: '4px 0 0',
  },
  sideStack: {
    display: 'grid',
    gap: '20px',
  },
  serviceForm: {
    display: 'grid',
    gap: '12px',
  },
  serviceList: {
    display: 'grid',
    gap: '10px',
  },
  historyBlock: {
    borderTop: '1px solid var(--border)',
    display: 'grid',
    gap: '12px',
    paddingTop: '14px',
  },
  historyQuoteRecord: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '8px',
    padding: '12px',
  },
  historyRecordHeader: {
    alignItems: 'start',
    display: 'flex',
    gap: '10px',
    justifyContent: 'space-between',
  },
  lockedFiscalPanel: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '12px',
    padding: '14px',
  },
  lockedFiscalGrid: {
    color: 'var(--muted)',
    display: 'grid',
    fontSize: '13px',
    gap: '6px',
  },
  treasuryMovementRow: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '14px',
    gridTemplateColumns: 'minmax(180px, 1fr) auto auto auto',
    padding: '14px 16px',
  },
  treasuryMovementRowCompact: {
    alignItems: 'start',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: '12px',
    padding: '14px',
  },
  treasuryOverviewStrip: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    padding: '14px 20px 0',
  },
  treasuryMovementPrimary: {
    display: 'grid',
    gap: '4px',
    minWidth: 0,
  },
  treasuryMovementMeta: {
    color: 'var(--muted)',
    fontSize: '13px',
    fontWeight: 600,
  },
  treasuryMovementAmount: {
    justifySelf: 'end',
    whiteSpace: 'nowrap',
  },
  treasuryMovementAmountCompact: {
    justifySelf: 'start',
  },
  treasuryActionGroup: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    justifyContent: 'flex-end',
  },
  treasuryActionGroupCompact: {
    justifyContent: 'flex-start',
  },
  treasuryRowFooter: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    justifyContent: 'space-between',
  },
  treasuryRowFooterCompact: {
    alignItems: 'start',
    display: 'grid',
    gap: '10px',
    justifyContent: 'stretch',
  },
  invoicePreview: {
    display: 'grid',
    gap: '14px',
    padding: '20px',
  },
  logoPreview: {
    maxHeight: '72px',
    maxWidth: 'min(180px, 42vw)',
    objectFit: 'contain',
  },
  logoPlaceholder: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px dashed var(--border)',
    borderRadius: '8px',
    color: 'var(--muted)',
    display: 'flex',
    fontWeight: 700,
    height: '72px',
    justifyContent: 'center',
    maxWidth: '180px',
    width: '42vw',
  },
  invoiceCompanyName: {
    fontSize: '20px',
    margin: 0,
  },
  pdfPreviewShell: {
    background: 'var(--panel-subtle)',
    display: 'flex',
    justifyContent: 'center',
    minWidth: 0,
    overflowX: 'hidden',
    padding: 'clamp(10px, 3vw, 20px)',
  },
  pdfPreviewPage: {
    background: '#ffffff',
    borderRadius: '6px',
    boxSizing: 'border-box',
    boxShadow: '0 18px 45px rgba(0, 0, 0, 0.28)',
    color: '#17202a',
    display: 'grid',
    gap: 'clamp(12px, 3vw, 18px)',
    maxWidth: '680px',
    minHeight: '720px',
    minWidth: 0,
    overflow: 'hidden',
    padding: 'clamp(14px, 4vw, 28px)',
    width: '100%',
  },
  pdfPreviewHeader: {
    alignItems: 'start',
    borderBottom: '1px solid #d9e0e7',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '16px',
    justifyContent: 'space-between',
    paddingBottom: '18px',
  },
  pdfPreviewMuted: {
    color: '#526071',
    fontSize: '13px',
    margin: '4px 0 0',
  },
  pdfPreviewMeta: {
    alignItems: 'start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '16px',
    justifyContent: 'space-between',
  },
  pdfPreviewClient: {
    display: 'grid',
    gap: '4px',
    minWidth: 0,
    textAlign: 'right',
  },
  pdfPreviewTable: {
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
    width: '100%',
  },
  pdfPreviewTh: {
    borderBottom: '1px solid #d9e0e7',
    color: '#526071',
    fontSize: 'clamp(10px, 2.7vw, 12px)',
    padding: '10px 6px',
    textAlign: 'left',
    textTransform: 'uppercase',
  },
  pdfPreviewThRight: {
    borderBottom: '1px solid #d9e0e7',
    color: '#526071',
    fontSize: 'clamp(10px, 2.7vw, 12px)',
    padding: '10px 6px',
    textAlign: 'right',
    textTransform: 'uppercase',
  },
  pdfPreviewTd: {
    borderBottom: '1px solid #edf1f5',
    fontSize: 'clamp(12px, 3.2vw, 14px)',
    overflowWrap: 'anywhere',
    padding: '12px 6px',
  },
  pdfPreviewTdRight: {
    borderBottom: '1px solid #edf1f5',
    fontSize: 'clamp(12px, 3.2vw, 14px)',
    fontWeight: 700,
    overflowWrap: 'anywhere',
    padding: '12px 6px',
    textAlign: 'right',
  },
  pdfPreviewTotals: {
    alignItems: 'end',
    display: 'grid',
    gap: '7px',
    justifyContent: 'end',
    maxWidth: '100%',
    overflowWrap: 'anywhere',
    textAlign: 'right',
  },
  pdfPreviewNotes: {
    background: '#f8fafc',
    border: '1px solid #e5eaf0',
    borderRadius: '6px',
    color: '#526071',
    fontSize: '13px',
    margin: 0,
    padding: '12px',
  },
  serviceRecord: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '8px',
    padding: '12px',
  },
  serviceDescription: {
    color: 'var(--muted)',
    fontSize: '13px',
    lineHeight: 1.45,
    margin: 0,
  },
  quoteList: {
    display: 'grid',
    gap: '10px',
    padding: '12px',
  },
  quoteListButton: {
    backgroundColor: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--text)',
    cursor: 'pointer',
    display: 'block',
    padding: '14px 16px',
    textAlign: 'left',
  },
  quoteListActive: {
    backgroundColor: 'var(--accent-soft)',
    border: '1px solid var(--accent)',
    borderRadius: '8px',
    color: 'var(--text)',
    cursor: 'pointer',
    display: 'block',
    padding: '14px 16px',
    textAlign: 'left',
  },
  quoteListCard: {
    alignItems: 'start',
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
  },
  quoteSelectionControl: {
    alignItems: 'flex-start',
    display: 'flex',
    paddingTop: '4px',
  },
  checkbox: {
    accentColor: 'var(--accent)',
    cursor: 'pointer',
    height: '16px',
    width: '16px',
  },
  quoteOpenButton: {
    alignItems: 'start',
    background: 'transparent',
    border: 0,
    color: 'inherit',
    cursor: 'pointer',
    display: 'grid',
    gap: '16px',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    padding: 0,
    textAlign: 'left',
    width: '100%',
  },
  quoteRowMain: {
    display: 'grid',
    gap: '5px',
    minWidth: 0,
  },
  quoteListAside: {
    alignItems: 'end',
    display: 'grid',
    gap: '8px',
    justifyItems: 'end',
  },
  quoteNumber: {
    color: 'var(--muted)',
    fontSize: '13px',
    fontWeight: 700,
  },
  quoteTitleText: {
    color: 'var(--text)',
    fontSize: '13px',
    fontWeight: 600,
  },
  quoteEditorSection: {
    display: 'grid',
    gap: '18px',
    padding: '18px 20px 22px',
  },
  quoteEditorSectionCompact: {
    padding: '14px',
  },
  quoteEditorBlock: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '14px',
    padding: '18px',
  },
  quoteEditorBlockCompact: {
    padding: '14px',
  },
  quoteSummaryGrid: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
  },
  quoteSummaryGridCompact: {
    gridTemplateColumns: 'minmax(0, 1fr)',
  },
  quoteSummaryCard: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '6px',
    minWidth: 0,
    padding: '12px',
  },
  quoteSummaryLabel: {
    color: 'var(--muted)',
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  inlineForm: {
    alignItems: 'end',
    borderBottom: '1px solid var(--border)',
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    padding: '16px 20px',
  },
  catalogPicker: {
    borderBottom: '1px solid var(--border)',
    display: 'grid',
    gap: '12px',
    padding: '16px 20px',
  },
  compactTitle: {
    fontSize: '16px',
    margin: 0,
  },
  helperText: {
    color: 'var(--muted)',
    fontSize: '13px',
    lineHeight: 1.5,
    margin: '6px 0 0',
  },
  quoteCatalogSurface: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '12px',
    padding: '14px',
  },
  quoteCatalogSurfaceCompact: {
    padding: '12px',
  },
  catalogGrid: {
    display: 'grid',
    gap: '10px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
  },
  catalogGridCompact: {
    gridTemplateColumns: 'minmax(0, 1fr)',
  },
  catalogItemButton: {
    alignItems: 'center',
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--text)',
    cursor: 'pointer',
    display: 'flex',
    gap: '10px',
    justifyContent: 'space-between',
    minHeight: '64px',
    padding: '12px 14px',
    textAlign: 'left',
  },
  catalogItemDescription: {
    color: 'var(--muted)',
    display: 'block',
    fontSize: '12px',
    fontWeight: 500,
    lineHeight: 1.3,
    marginTop: '3px',
  },
  catalogItemPrice: {
    color: 'var(--accent)',
    fontSize: '13px',
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  costCatalogList: {
    display: 'grid',
    gap: '10px',
    padding: '12px',
  },
  costCatalogCard: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '12px',
    padding: '14px',
  },
  costCatalogCardHeader: {
    alignItems: 'start',
    display: 'flex',
    gap: '10px',
    justifyContent: 'space-between',
  },
  costCatalogCardTitle: {
    display: 'grid',
    gap: '4px',
    minWidth: 0,
  },
  costCatalogCardFacts: {
    display: 'grid',
    gap: '8px',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
  },
  costCatalogFact: {
    display: 'grid',
    gap: '4px',
    minWidth: 0,
  },
  costCatalogFactLabel: {
    color: 'var(--muted)',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  costCatalogCardActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    justifyContent: 'flex-start',
  },
  mutedText: {
    color: 'var(--muted)',
    fontSize: '13px',
  },
  membershipPaymentList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginTop: '4px',
  },
  membershipPaymentCard: {
    alignItems: 'center',
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    justifyContent: 'space-between',
    padding: '10px 12px',
  },
  membershipPaymentSummary: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  membershipPaymentRow: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  membershipPaymentChip: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    color: 'var(--muted)',
    display: 'inline-flex',
    fontSize: '12px',
    padding: '5px 9px',
  },
  membershipPaymentActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  platformMembershipHistoryCard: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '10px',
    padding: '14px',
  },
  platformMembershipHistoryBody: {
    display: 'grid',
    gap: '6px',
  },
  totals: {
    alignItems: 'center',
    borderTop: '1px solid var(--border)',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '20px',
    justifyContent: 'flex-end',
    padding: '18px 0 0',
  },
  totalsCompact: {
    alignItems: 'stretch',
    display: 'grid',
    gap: '8px',
    justifyContent: 'stretch',
  },
  quoteItemCardList: {
    display: 'grid',
    gap: '10px',
  },
  quoteItemCard: {
    background: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    display: 'grid',
    gap: '10px',
    padding: '12px',
  },
  quoteItemCardHeader: {
    alignItems: 'start',
    display: 'flex',
    gap: '10px',
    justifyContent: 'space-between',
  },
  quoteItemCardBody: {
    display: 'grid',
    gap: '8px',
  },
  quoteItemFactGrid: {
    display: 'grid',
    gap: '8px',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
  },
  quoteItemFact: {
    display: 'grid',
    gap: '4px',
    minWidth: 0,
  },
  quoteItemFactLabel: {
    color: 'var(--muted)',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  filterBar: {
    alignItems: 'end',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    gap: '12px',
    padding: '14px 20px',
  },
  quoteFilterBar: {
    borderBottom: '1px solid var(--border)',
    display: 'grid',
    gap: '10px',
    padding: '14px 20px',
  },
  bulkActionBar: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    justifyContent: 'space-between',
  },
  bulkActionText: {
    color: 'var(--muted)',
    fontSize: '13px',
    fontWeight: 700,
  },
  compactLabel: {
    color: 'var(--muted)',
    display: 'grid',
    flex: 1,
    fontSize: '12px',
    fontWeight: 700,
    gap: '6px',
    textTransform: 'uppercase',
  },
  searchInput: {
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    color: 'var(--text)',
    font: 'inherit',
    fontSize: '14px',
    padding: '9px 10px',
    textTransform: 'none',
  },
  chartList: {
    display: 'grid',
    gap: '14px',
    padding: '18px 20px',
  },
  chartRow: {
    display: 'grid',
    gap: '7px',
  },
  chartLabelRow: {
    alignItems: 'center',
    display: 'flex',
    gap: '12px',
    justifyContent: 'space-between',
  },
  chartSecondary: {
    color: 'var(--muted)',
    fontSize: '12px',
    margin: 0,
  },
  chartTrack: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    height: '12px',
    overflow: 'hidden',
  },
  chartBar: {
    background: 'linear-gradient(90deg, var(--accent), #25d366)',
    display: 'block',
    height: '100%',
  },
  smartReportGrid: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    padding: '18px 20px',
  },
  smartInsight: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    color: 'var(--text)',
    display: 'grid',
    gap: '6px',
    lineHeight: 1.45,
    padding: '14px',
  },
  filterSelect: {
    background: 'var(--input-bg)',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    color: 'var(--text)',
    font: 'inherit',
    fontSize: '14px',
    minWidth: '130px',
    padding: '9px 10px',
    textTransform: 'none',
  },
  statusFilterRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  filterChip: {
    backgroundColor: 'var(--panel-bg)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    color: 'var(--text)',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 700,
    padding: '6px 9px',
  },
  filterChipActive: {
    backgroundColor: 'var(--accent)',
    border: '1px solid var(--accent)',
    borderRadius: '999px',
    color: 'var(--accent-contrast)',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 700,
    padding: '6px 9px',
  },
  statusBadge: {
    borderRadius: '999px',
    display: 'inline-flex',
    fontSize: '12px',
    fontWeight: 700,
    justifySelf: 'start',
    lineHeight: 1,
    padding: '6px 8px',
  },
  statusDraft: {
    background: 'var(--panel-subtle)',
    color: 'var(--muted)',
  },
  statusIssued: {
    background: 'var(--accent-soft)',
    color: 'var(--accent)',
  },
  statusAccepted: {
    background: 'var(--success-bg)',
    color: 'var(--success)',
  },
  statusRejected: {
    background: 'var(--danger-bg)',
    color: 'var(--danger)',
  },
  activeMembershipBadge: {
    background: 'var(--success-bg)',
    color: 'var(--success)',
  },
  expiredMembershipBadge: {
    background: 'var(--danger-bg)',
    color: 'var(--danger)',
  },
  historyAcceptedBadge: {
    background: 'var(--success-bg)',
    color: 'var(--success)',
  },
  historyRejectedBadge: {
    background: 'var(--danger-bg)',
    color: 'var(--danger)',
  },
  categoryBadge: {
    background: 'var(--panel-subtle)',
    border: '1px solid var(--border)',
    borderRadius: '999px',
    color: 'var(--text)',
    display: 'inline-flex',
    fontSize: '12px',
    fontWeight: 700,
    lineHeight: 1,
    padding: '6px 8px',
  },
  detailMeta: {
    alignItems: 'center',
    color: 'var(--muted)',
    display: 'flex',
    fontSize: '13px',
    gap: '8px',
    marginTop: '6px',
  },
  progressBar: {
    alignItems: 'center',
    borderBottom: '1px solid var(--border)',
    display: 'grid',
    gap: '10px',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    padding: '16px 20px',
  },
  progressStep: {
    alignItems: 'center',
    display: 'flex',
    gap: '8px',
  },
  progressDot: {
    background: 'var(--muted)',
    borderRadius: '999px',
    display: 'inline-block',
    height: '10px',
    width: '10px',
  },
  progressDotDone: {
    background: 'var(--success)',
    borderRadius: '999px',
    display: 'inline-block',
    height: '10px',
    width: '10px',
  },
  progressLabel: {
    color: 'var(--muted)',
    fontSize: '13px',
    fontWeight: 700,
  },
  progressLabelDone: {
    color: 'var(--text)',
    fontSize: '13px',
    fontWeight: 700,
  },
} satisfies Record<string, CSSProperties>;

